site_name: DCAN Labs readthedocs

theme: rtd-dropdown

plugins:
    - search
    
docs_dir: docs

nav: 
    - Welcome: index.md
    - Studies and Groups: studies.md
    - Accessing Servers:
        - Minnesota Supercomputing Institute (MSI): access/msi.md
        - Data Transfers:
            - DICOM Transfers (CMRR-UMN): access/data/dicom.md
            - Within Institution: access/data/within.md
            - Between Institutions: access/data/between.md
    - Coding Standards: code.md
    - Software Versioning: softwareversioning.md
    - Programming Languages: lang.md 
    - Containers: contain.md
    - Pipeline Pre-Processing:
        - Locating DICOMs: pipeline/locate.md
        - Moving DICOMs to Server: pipeline/move.md
        - DICOMs to NIFTIs: pipeline/dn.md
        - QC-ing NIFTIs: pipeline/qc.md
        - Respiration Rate Settings: pipeline/respir.md
    - Manual Processing via DCAN Pipelines:
        - ABCD: manualpro/abcd.md
        - Infant Team:
            - Infant Pipeline Documentation: manualpro/infant/pipeline.md
            - Fixing Common Errors: manualpro/infant/error.md
            - Templates for Brain Extraction: manualpro/infant/template.md
            - Quality Control for Infant Data: manualpro/infant/qc.md
            - Troubleshooting: manualpro/infant/troubleshooting.md
        - NHP: manualpro/nhp.md
        - Rodent: manualpro/rodent.md
    - Cleaning Intermediate Files:
        - Custom Clean: clean/custom.md
        - Filemapper: clean/filemap.md
    - DCAN Processing Tools:
        - BIDS GUI: protool/bids.md
        - DADS App: protool/dads.md
    - Neuroimaging Software: software.md
    - DCAN Analysis Tools:
        - Seed Map Parcellation Wrapper: analysis/seed.md
        - PALM: 
            - Overview: analysis/palm/intro.md
            - Code and SOP: analysis/palm/code.md
            - Release History: analysis/palm/release.md
        - Template Matching: analysis/temp.md
        - Random Forest: 
            - Overview: analysis/forest/intro.md
            - Code and SOP: analysis/forest/code.md
            - Release History: analysis/forest/release.md
        - F Conn Regression: analysis/fconn/intro.md
        - Cifti Conn Matrix: analysis/cifti.md
        - Community Detection: analysis/comm/intro.md
        - Marginal Model CIFTI:
            - Overview: analysis/marg/intro.md
            - Code and SOP: analysis/marg/code.md
            - Release History: analysis/marg/release.md
        - Automated Subset Analysis:
            - Overview: analysis/auto/intro.md
            - Code and SOP: analysis/auto/code.md
            - Release History: analysis/auto/release.md
        - BWAS: analysis/bwas.md
        - Poly Conn:
            - Overview: analysis/poly/intro.md
            - Code and SOP: analysis/poly/code.md
            - Release History: analysis/poly/release.md
        - Video Walkthroughs: analysis/video.md
    - DCAN Visualization Tools:
        - Figure Maker: visual/figure.md
        - ShowM: visual/show/code.md
        - Plot Histogram:
            - Code and SOP: visual/plot/code.md
            - Video Walkthrough: visual/plot/video.md
            - Release History: visual/plot/release.md
        - Skinny Plot: visual/skin/code.md 
    - Utility Tools:
        - Downloading from NDA: utility/nda.md
        - Filemapper: utility/filemap.md
        - GUI Environment: utility/gui.md
        - Reference Bias Checker: utility/bias.md
    - UMN Recommended Courses: courses.md
    - Troubleshooting: trouble.md
    - Recorded Presentations: didactic.md
    - Linux: linux.md
    - Contributors: contributors.md
